import dynamic from "next/dynamic";
import Head from "next/head";

import Hero from "@/components/Hero";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Feedbacks from "@/components/Contact/Feedbacks";
const About = dynamic(() => import("@/components/About"));
const Programs = dynamic(() => import("@/components/Programs"));
const Steps = dynamic(() => import("@/components/Steps"));
const FAQ = dynamic(() => import("@/components/FAQ"));
const Review = dynamic(() => import("@/components/Review"));
const Gallery = dynamic(() => import("@/components/Gallery"));
const Contact = dynamic(() => import("@/components/Contact"));

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header />
        <Hero />
        <About />
        <Programs />
        <Steps />
        <FAQ />
        <Review />
        <Gallery />
        <Contact />
        <Feedbacks />
        <Footer />
      </>
    </>
  );
};
export default Home;
